# Generated by Django 4.2.1 on 2023-06-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0004_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
    ]
