# Generated by Django 4.2.1 on 2023-06-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0005_patient_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='relative_phone_nubmer',
            new_name='relative_phone_number',
        ),
    ]
