# Generated by Django 4.2.1 on 2023-06-07 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0006_rename_relative_phone_nubmer_patient_relative_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
