# Generated by Django 4.2.1 on 2023-06-11 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0007_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esp',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.patient'),
        ),
        migrations.AlterField(
            model_name='vital',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.patient'),
        ),
    ]
