# Generated by Django 4.2.1 on 2023-06-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edge', '0008_alter_esp_userid_alter_vital_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vital',
            name='espID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='edge.esp'),
        ),
    ]
